### ISSUE TITLE
Cannot scroll up on transfer page

### ISSUE THREAD

**Issue by afterconnery** [turtlecoin/turtlecoin-mobile-wallet#101]
**Describe the bug**
Unable to scroll up and view all of my contacts to send TRTL to.

**To Reproduce**
1. Go to "transfer" page
2. Try to scroll up

**Expected behavior**
To scroll up and see all my contacts I can send TRTL to.

**Environment**
- App version 1.0.0
- Android 7.1.1

**Comment by zpalmtree** [comment]
Hiya,

Sorry I haven't got to this yet, been very busy. This is probably a very easy fix, just need to swap a `<View>` with a `<ScrollView>`

**Comment by zpalmtree** [comment]
Fixed. Will be in the next update.
