### ISSUE TITLE
Problems when using trtlbutton qr code

### ISSUE THREAD

**Issue by afterconnery** [turtlecoin/turtlecoin-mobile-wallet#107]
So, I have added a trtlbutton on my website https://afterconnery.github.io 

When I scan the qr code with Tonchan it brings up the recipient's name page to fill out. I fill it out and then hit continue. Then it sends me to the transaction review page. The turtle button is set for 10,000 TRTL, but with the node and developer fee it will be less than the 10,000 TRTL the button is looking for. I still sent the payment to see what would happen. Then the dialog box said that I still need to send the rest. I exited out of the dialog box on the computer and so the 9,945 TRTL or whatever never made it back to me (oh, well). ( I was testing it out before I put something in the weekly update)

So, the problem is that when using the qr code for trtlbutton I cannot adjust the total amount i should send so that I fulfill the required amount the button needs for the process.

**Comment by zpalmtree** [comment]
Fixed.
