### ISSUE TITLE
NO balance found

### ISSUE THREAD

**Issue by a20180502** [turtlecoin/turtlecoin-mobile-wallet#108]
Default daemon to use a ConventionalDaemon(url, port)，such as 
**this.defaultDaemon = new Daemon('100.1.200.12', 11222);**

Payment through PC Wallet :
Outgoing transfer:
Hash: f3a1cde5c245607c651014135d0eb66e007f28b3342fa887f2290aff24e4e0dd

but the balance received by mobile wallet is 0
Does it support conventionaldaemon mode

**Comment by zpalmtree** [comment]
> Does it support conventionaldaemon mode

Yes it does. Sorry, I don't have much time to support fork issues.
