### ISSUE TITLE
Update 'dock' icon

### ISSUE THREAD

**Issue by zpalmtree** [turtlecoin/turtlecoin-mobile-wallet#11]
I'm not really sure what the term for this is, but when you hit the burger button to view all your open apps, we're using a default android logo.

![image](https://user-images.githubusercontent.com/22151537/53283544-14ecab00-3740-11e9-8796-cf34b5bba5ef.png)

**Comment by brandonlehmann** [comment]
I believe this may be related? https://medium.com/react-native-training/how-to-easily-configure-launch-icons-in-react-native-android-ios-2e1f351496ed

**Comment by zpalmtree** [comment]
I'm fairly sure I used that tool to generate my icons :stuck_out_tongue:

**Comment by wrkzdev** [comment]
I normally used this: https://romannurik.github.io/AndroidAssetStudio/icons-launcher.html
Option for square / round. Also should add

`android:roundIcon="@mipmap/ic_launcher_round"` in AndroidManifest.xml

**Comment by TheDOme6** [comment]
Hmm dock icon is shown on oneplus.
http://www.image-share.com/ijpg-3941-167.html

**Comment by zpalmtree** [comment]
I just looked again on my device, and it's now displaying... no idea when that got fixed!
