### ISSUE TITLE
Allow generating customized QR codes

### ISSUE THREAD

**Issue by zpalmtree** [turtlecoin/turtlecoin-mobile-wallet#112]
So users can make payment requests to other users. If we wanted to get a bit fancier, we could store these payment requests, allowing them to be marked as received.

**Comment by jeanhqi** [comment]
how i can find my payment id and remark in my wallet ?
![Screenshot_20210103-151638](https://user-images.githubusercontent.com/71483067/103477769-11fc8000-4dd7-11eb-8c10-804813e5a5d1.png)


to withdraw my token to my wallet?

**Comment by jeanhqi** [comment]
i can't find payment id

**Comment by zpalmtree** [comment]
> 
> 
> i can't find payment id

You don't need a payment ID to withdraw to your wallet. Leave the field blank.
Please open a new issue if you are having trouble, this is an issue for something else.
