### ISSUE TITLE
Not syncing in background

### ISSUE THREAD

**Issue by elkimek** [turtlecoin/turtlecoin-mobile-wallet#118]
**Describe the bug**
Wallet is not syncing in bacground

**To Reproduce**
1. Start sync
2. Go to background/another app etc.

**Expected behavior**
Syncing should continue in background

**Environment**
- App version v1.1.2
- GrapheneOS
- Pixel 3a

**Additional context**
Output of `adb logcat *:W` when sending the app to the background:

```
02-13 18:14:31.637   759  2797 E audio_hw_utils: audio_extn_utils_send_app_type_cfg: Failed to derive app_type for uc type : 0x1
02-13 18:14:31.638   759  2797 E ACDB-LOADER: Error: ACDB AudProc vol returned = -19
02-13 18:14:31.678   759  2797 E ACDB-LOADER: Error: ACDB AudProc vol returned = -19
02-13 18:14:31.739 16265 16319 W Notification: Use of stream types is deprecated for operations other than volume control
02-13 18:14:31.739 16265 16319 W Notification: See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case
02-13 18:14:31.816  1995  2190 W System  : A resource failed to call release.
```

Output of `adb logcat *:W -e com.tonchan` throws no error when sending the app to the background but when going back to the app from background I'm getting:

```
02-13 18:24:36.407   988  1267 W WindowManager: TaskSnapshotSurface.create: Failed to find main window for token=AppWindowToken{ed0fac7 token=Token{6ee4406 ActivityRecord{d3ffee1 u0 com.tonchan/.MainActivity t1129}}}
02-13 18:24:36.922   631   631 E Layer   : [Surface(name=AppWindowToken{ed0fac7 token=Token{6ee4406 ActivityRecord{d3ffee1 u0 com.tonchan/.MainActivity t1129}}})/@0x189bdd5 - animation-leash#0] No local sync point found
```

**Comment by zpalmtree** [comment]
Sync will not being in the background upon initial launch until about 15 minutes have passed. 

See https://github.com/transistorsoft/react-native-background-fetch

> There is no way to increase the rate which a fetch-event occurs and this plugin sets the rate to the most frequent possible — you will never receive an event faster than 15 minutes. The operating-system will automatically throttle the rate the background-fetch events occur based upon usage patterns. Eg: if user hasn't turned on their phone for a long period of time, fetch events will occur less frequently.

You can decrease the throttling by disabling doze mode (see settings), and you can verify that background sync is working as expected by manually simulating a background fetch event:

`adb shell cmd jobscheduler run -f com.tonchan 999`
