### ISSUE TITLE
Error: Build Failed with an exception ...

### ISSUE THREAD

**Issue by JustFragger** [turtlecoin/turtlecoin-mobile-wallet#126]
**Good Day/Afternoon** ! So I want build app from this source code, I edited config and all these stuff which needs to be edited , but at last when using `gradlew assembleRelease`, to get build, after entering command i get this error :

`:ReactNative:Unexpected empty result of running '[node, C:\Users\Mathew\Desktop\wallet-master\node_modules\@react-native-community\cli\build\bin.js, config]' command.
:ReactNative:Running '[node, C:\Users\Mathew\Desktop\wallet-master\node_modules\@react-native-community\cli\build\bin.js, config]' command failed.

FAILURE: Build failed with an exception.

Where:
Script 'C:\Users\Mathew\Desktop\wallet-master\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' line: 195`

What went wrong:
A problem occurred evaluating script.
> internal/modules/cjs/loader.js:1032  throw err;  ^Error: Cannot find module 'C:\Users\Mathew\Desktop\wallet-master\node_modules\@react-native-community\cli\build\bin.js'    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)    at Function.Module._load (internal/modules/cjs/loader.js:898:27)    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)    at internal/main/run_main_module.js:17:47 {  code: 'MODULE_NOT_FOUND',  requireStack: []}`

**I"m using node.js (npm) , yarn , and react native (which is installed with `yarn install`)**

I"m out of ideas what is wrong and what module is missing (not found ) :/

Any help is appreciated :)

Kind Regards
-Mathew S.

**Comment by 0des** [comment]
Unfortunately we do not support forks, thank you.

**Comment by JustFragger** [comment]
> Unfortunately we do not support forks, thank you.

Nice, Thanks for ur time

**Comment by JustFragger** [comment]
Devs doesn"t support forks , closed //
