### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by hooman136** [turtlecoin/turtlecoin-mobile-wallet#141]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
- App version [e.g. v0.0.6] (You can find this in settings)
- Android version, if known [e.g. Android 7]
- Phone model, if known [e.g. Pixel 2]

**Additional context**

**Comment by brandonlehmann** [comment]
No reported information?

**Comment by zpalmtree** [comment]
Fill out the template please.
