### ISSUE TITLE
UI is not that good

### ISSUE THREAD

**Issue by shynvn** [turtlecoin/turtlecoin-mobile-wallet#143]
Hi
It's not a problem actually
But the app UI is just bad
It's a shame because the app has a very powerful core but the UI is like 2009 android apps
It will be super nice if you guys create a more good looking UI :)

**Comment by zpalmtree** [comment]
Maybe you could demonstrate some of your UI/UX skills and open a pull request, Shayan. If not, well, i quite like how it is right now.
