### ISSUE TITLE
Cannot transfer

### ISSUE THREAD

**Issue by alfredosalzillo** [turtlecoin/turtlecoin-mobile-wallet#144]
**Describe the bug**
Trying to transfer I get this error 

```
StatusCodeError: 409 -error":code": 65, 'message":"Transaction contains an input which has already been spent'}
```

**Environment**
- App version  v1.1.2]
- Android version, if known Android 11
- Phone model, if known Pixel 4xl

**Comment by brandonlehmann** [comment]
Have you tried resyncing the wallet ? That usually resolves such issues as the wallet currently believes that it can spend funds that it has already spent.

**Comment by alfredosalzillo** [comment]
I'm resyncing. But it's strange i've never sent from this wallet only received.

**Comment by brandonlehmann** [comment]
But it has very likely optimized itself and sent fusion transactions so it has indeed sent :)
