### ISSUE TITLE
Wallet block synchronizing problem

### ISSUE THREAD

**Issue by halimuygun** [turtlecoin/turtlecoin-mobile-wallet#146]
Hello! I have solo mined turtlecoin and i found a block. But i cant see reward and transaction in my wallet. On settings, i turn on coinbase transactions. I checked this block with my adress and private view key on block explorer but still i dont have my reward. 

And this is very interesting; Im using TonChan wallet. When block synchronizing arrived my block height, it stops and dont synchronize anymore? I rewinded wallet many times. What is wrong i dont understand?

Transaction : 6557f358402ee02e898683a00a8a93060d987b2d0fe3a371cda2d1b2e88170ce
Block Height : 3,544,956

-   Version Used : TonChan v1.2.2
-   Operating System and version : Android 10
-   Phone Model : Redmi Nore 7

![IMG_20210504_102934](https://user-images.githubusercontent.com/8327906/116973258-ed50e000-acc4-11eb-8235-e2e1605a6474.jpg)

**Comment by zpalmtree** [comment]
Can you check the logs screen under settings? There was a bug where v1.2.1 would not find coinbase transactions, but it should have been fixed in v1.2.2.

**Comment by halimuygun** [comment]
Hi, i got this block only with Zedwallet. Mobile app and Windows app cant get this block.

![IMG_20210505_104554](https://user-images.githubusercontent.com/8327906/117110727-41c09200-ad8f-11eb-9501-db187abc33e2.jpg)

**Comment by zpalmtree** [comment]
Thanks for the logs, that helped me track down the bug. It should be fixed in v1.2.3, it might take some hours/days to get distributed to your play store.

Please open up an issue on the repos of whatever other wallet apps you were having issues finding the transaction on, so we can fix those as well.

**Comment by halimuygun** [comment]
It fixed. I get block reward. Thank you!
