### ISSUE TITLE
how can i run this app ?

### ISSUE THREAD

**Issue by ahmad923245** [turtlecoin/turtlecoin-mobile-wallet#150]

**Comment by zpalmtree** [comment]
Install it from the play store or the `.apk` on the releases page

**Comment by ahmad923245** [comment]
where is release page?
and i am talking about how to setup in my laptop like when i try to run
command yarn install it give me error '.' is not recognize kindly help to
run this app on my laptop

**Comment by zpalmtree** [comment]
This is a mobile wallet, you can't run it on your laptop.

**Comment by ahmad923245** [comment]
ohh so how can i get the apk of this? maybe release apk

**Comment by ahmad923245** [comment]
i mean to say i am React native Developer and i want to install node
modules of this app and do some changes like UI of then i want to make apk
of that ..you have idea how can i do that?

**Comment by brandonlehmann** [comment]
> i mean to say i am React native Developer and i want to install node modules of this app and do some changes like UI of then i want to make apk of that ..you have idea how can i do that?
> […](#)

Which fork project are you with?

**Comment by ahmad923245** [comment]
not now

**Comment by ahmad923245** [comment]
actually i clone this repo and now i want to run it on react native develop envi 

can you help me ?
or tell me how can i get the apk of this
