### ISSUE TITLE
Sync bar not showing in landscape view.

### ISSUE THREAD

**Issue by Menksy** [turtlecoin/turtlecoin-mobile-wallet#22]
![screenshot_20190227-174311](https://user-images.githubusercontent.com/48073306/53531351-ab122f80-3ab8-11e9-99fe-e7bf3b8bb980.png)
![screenshot_20190227-174259](https://user-images.githubusercontent.com/48073306/53531355-ac435c80-3ab8-11e9-9ab8-cf035e03b05b.png)

**Comment by zpalmtree** [comment]
I may just disable landscape view. I don't see much gain for it, and it needs all pages to be redesigned.

**Comment by Menksy** [comment]
I think that would be a good idea. I dont see the need or gain from it either.

**Comment by zpalmtree** [comment]
Fixed in https://github.com/turtlecoin/turtlecoin-mobile-wallet/commit/5072a34f3342bda0600f14814ae090a7e1f16962
