### ISSUE TITLE
Sync only when wallet app is open on home screen.

### ISSUE THREAD

**Issue by Menksy** [turtlecoin/turtlecoin-mobile-wallet#25]
Sync slows down or stops when app is running in background or phone goes to sleep. Only fully syncs when app is open on the home screen.

**Comment by zpalmtree** [comment]
The wallet does sync in the background. However, approximately 15 minutes have to pass for this to occur. Every 15 minutes, the wallet syncs for 14 minutes in the background.

**Comment by Menksy** [comment]
When I had my wallet running in background for 18 hours it synced about 3%. When I set my phone to never go to sleep and left the app open I got to 30% 20 hours later.

**Comment by zpalmtree** [comment]
Possibly related - https://dontkillmyapp.com/ - It's working fine for me. I'm planning on adding a logger shortly, so we'll have a little more insight into what's going on wrt background sync.

**Comment by Menksy** [comment]
I'm looking into my phone settings. I heard of a few other people with the same issue.

**Comment by zpalmtree** [comment]
Logger added, and an FAQ has been added regarding background sync.
