### ISSUE TITLE
Share button

### ISSUE THREAD

**Issue by Menksy** [turtlecoin/turtlecoin-mobile-wallet#27]
Add a share button in settings?

Allow users to share the app or their wallet to other social platforms or users.

**Comment by zpalmtree** [comment]
I don't really know what you mean by that tbh

**Comment by Menksy** [comment]
The ability to rate and share the app?

**Comment by zpalmtree** [comment]
OK, I was thinking about adding a link to the play store to rate it, is that what you mean?

**Comment by Menksy** [comment]
Yes exactly. 

Also,
If for example if I wanted to share the TonChan App with my friends on facebook, whats the easiest way to do so? Thats where I was thinking of a share button of sorts.

**Comment by zpalmtree** [comment]
I guess the most versatile method would just be copying the google play link to the clipboard?

**Comment by zpalmtree** [comment]
Done.
