### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by zpalmtree** [turtlecoin/turtlecoin-mobile-wallet#3]

**Comment by brandonlehmann** [comment]
https://docs.travis-ci.com/user/languages/android

Leaving here and maybe I'll try giving you a hand.

**Comment by zpalmtree** [comment]
I started on this, but trashed my branch when I swapped repos

**Comment by zpalmtree** [comment]
meh, doesn't really gain us much when the javascript isn't type checked
