### ISSUE TITLE
QR Scan to pay feature

### ISSUE THREAD

**Issue by wrkzdev** [turtlecoin/turtlecoin-mobile-wallet#33]
It is good if there the mobile wallet just scan a generated QR code and it translates automatically to address (or integrated address) + amount? And tap on Confirmation => Sent.

On payee's side, they can generate a QR to request payment either from mobile or web.

**Comment by zpalmtree** [comment]
Not hard to do.. I was planning on swapping the amount -> address screen around anyway. I would like a standardized format so I don't end up having to support multiple ones. I'm not sure what the convention is for multiple values in a QR code.

**Comment by zpalmtree** [comment]
Proposed format - in use by TurtlePay - `turtlecoin://TRTLuzbkEepSJdmqkMJ11APWaazS8aat2Vmobbve6GA1D8FfMr7PAZZMJv7TozUXaw5y7DN2n626P54J465fhDmFatRSnp61Vkv?amount=100`

**Comment by zpalmtree** [comment]
Also need a `name` parameter for filling in the confirmation screen. Will allow spaces, so will be uri encoded.

**Comment by brandonlehmann** [comment]
Added via TurtlePay https://github.com/TurtlePay/turtlepay-public-api/commit/a52a739f9a40cf95bfdfa7b515728e776e6179f9  -- deploying momentarily

**Comment by brandonlehmann** [comment]
> Added via TurtlePay [TurtlePay/turtlepay-public-api@a52a739](https://github.com/TurtlePay/turtlepay-public-api/commit/a52a739f9a40cf95bfdfa7b515728e776e6179f9) -- deploying momentarily

deployed

**Comment by wrkzdev** [comment]
sendToAddress is either Standard address or integrated address? And payment id?

**Comment by brandonlehmann** [comment]
Should be either. If separated our I would think the uri param would be something like `id`

**Comment by zpalmtree** [comment]
Added: https://github.com/turtlecoin/turtlecoin-mobile-wallet#integrating-qr-codes
