### ISSUE TITLE
Backup and Delete wallet should ask for PIN

### ISSUE THREAD

**Issue by wrkzdev** [turtlecoin/turtlecoin-mobile-wallet#37]
These two functions in **Settings** tab should always ask for PIN before display keys or before delete the wallet.

**Comment by wrkzdev** [comment]
And also before sending TX? After **Transfer** is tapped.

**Comment by zpalmtree** [comment]
On the one hand I don't disagree, on the other, I feel transferring is very quick and friction-less when you use a QR code, and I don't want to impede that.

**Comment by thinkpol2** [comment]
I really like the transfer process as is, quick and easy. I could see why some would want an extra confirmation, though. Maybe a setting?

**Comment by wrkzdev** [comment]
Yes, setting Confirmation for any TX with PIN to be on or off?

**Comment by zpalmtree** [comment]
Great idea. I'll do that.

**Comment by zpalmtree** [comment]
Done.

**Comment by zpalmtree** [comment]
Forgot to add to the Delete Wallet option, and (derp) the toggle pin security option.

**Comment by zpalmtree** [comment]
Should be fixed now.
