### ISSUE TITLE
Wallet crash and now won't open

### ISSUE THREAD

**Issue by Judderz** [turtlecoin/turtlecoin-mobile-wallet#39]
All was synching fine (albeit slowly), got to around 650000 blockheight (approx 52%) and synching stopped, app restarted, wallet no longer available. Options are to create wallet, or recover wallet. I enter keys to recover wallet, I've tried:
Pick a month wallet created
Approx blockheight
Recover from Keys

Each time I try, the app crashes (see image as to what happens)

![tonchan-crash](https://user-images.githubusercontent.com/37659559/53942274-3f305800-40b2-11e9-9dd6-1450dc033946.jpg)

Cheers

Judderz

**Comment by zpalmtree** [comment]
I think I have an idea what might be going wrong, but not 100%..

Could you try disabling wifi/data before launching the wallet, and see if it still crashes?
I think your issue will probably be fixed by reinstalling.

I really need to find a way to get crash logs from devices easily..

**Comment by zpalmtree** [comment]
Probably related:

> OK. I think something went wrong when opening your wallet, and when that happens, it marks it as no longer existing, to prevent infinite loops. However, I don't actually ever delete the wallet when that occurs, so it probably caused the saving to fail, until you reinstalled. I'm not sure what caused the loading to fail, but i'll fix it marking the wallet as deleted, and just display the error, so I can try and fix that when it occurs.

**Comment by zpalmtree** [comment]
Actually... I wonder if it's possible the background save (every 60 seconds) can conflict with the save when doing background syncing... possibly if they are both called at the same time, it could go wrong.

**Comment by Judderz** [comment]
Tried the disabling of wifi/data, that didn't work.

I uninstalled and installed again, and had to start from scratch synching (loving the new look too), seems to be synching faster too.  Will let you know how I get on :)

**Comment by zpalmtree** [comment]
OK..

* I have disabled the wallet being deleted when it fails to load. It should now print an error when loading fails.
* I have added a crash logger to help fix any crashes.
* I have attempted to prevent two saves occurring at once.
* I synced from 640k to 700k successfully, not sure what was causing that crash.

I'll be making a new play store release relatively soon with these changes.

**Comment by zpalmtree** [comment]
Closing for now, feel free to reopen if it still occurs with v0.0.5.
