### ISSUE TITLE
After sending a transaction to TonChan Wallet it will no longer syncronize it

### ISSUE THREAD

**Issue by Nash-Cash** [turtlecoin/turtlecoin-mobile-wallet#41]
hey guys, i have a problem with TonChans.. in the config i tried the connection with the blockchain-cache-api and the conventional daemon. it syncronizes so far correctly. but as soon as i want to transfer something to tonchan, the syncronization breaks off and debug log says: Eoor procressing block 12345. this call is not supported on the cache api. the cache api returns global indexes directly fom /getWalletSyncData

I don't have an idea anymore.

**Comment by zpalmtree** [comment]
Can you clarify what daemon setup you are currently using that gives the error

**Comment by Nash-Cash** [comment]
in my config i have 
defaultDaemon: new BlockchainCacheApi('167.xx.xxx.148', 24888), 

on droplet i start with ./NashCashd --enable-cors="*" --enable-blockexplorer --rpc-bind-ip=0.0.0.0 --rpc-bind-port=24888

i also used this configuration: blockchain-cache-api & blockchain-data-collection-agent. There I entered the url and set ssl (I still have to configure) to false, but it  stops at the block where the transaction is located.

**Comment by zpalmtree** [comment]
If it's not a blockchain api, then don't use it like one...

Instead do `new ConventionalDaemon(''167.xx.xxx.148', 24888),`

If the error continues, report back.

**Comment by Nash-Cash** [comment]
I tried that, but I'm gonna try it again.  (''16..... < -- with two quotation mark

**Comment by zpalmtree** [comment]
Typo, sorry

**Comment by Nash-Cash** [comment]
i just tested it again. the error remains. exact the block in which the transaction to the wallet is. there he stops and outputs the error with the api call

**Comment by zpalmtree** [comment]
OK, I will investigate

**Comment by zpalmtree** [comment]
I cannot reproduce this. All I did was change

```
defaultDaemon: new BlockchainCacheApi('blockapi.turtlepay.io', true),
```
to
```
defaultDaemon: new ConventionalDaemon('public.turtlenode.online', 11898),
```

Then I created a wallet, sent a transaction, and it received it fine. It could also send an outgoing transaction correctly. Can you try deleting your current wallet, creating a fresh wallet, ensuring you are using `ConventionalDaemon`, and then try sending a transaction again?

**Comment by zpalmtree** [comment]
Reopen if you can't get this fixed, preferably with a link to your repository.
