### ISSUE TITLE
Alternating home screens each launch

### ISSUE THREAD

**Issue by old-greywolf** [turtlecoin/turtlecoin-mobile-wallet#44]
Samsung Galaxy Note 5
Android version 7.0
behavior noted today, 03/07/19

this just started this evening.  i open the wallet with PIN, and see a correct balance, with fiat value, but the sync progress shows 0% and does not change.  see the file no-sync.png.
i exit the wallet by using the back button on the phone screen control.
i open the wallet again with PIN and the balance is blank and the area for sync progress is blank.
see the file no-ba;ance.png.
i exit the wallet by using the back button on the phone screen control.

i open the wallet again with PIN and the 2 cycle display-switching loops
![no-sync](https://user-images.githubusercontent.com/34691947/54005565-c6abb480-410e-11e9-8146-62fd6d984cce.png)
![no-balance](https://user-images.githubusercontent.com/34691947/54005580-d6c39400-410e-11e9-8977-a613eac4cba9.png)

**Comment by zpalmtree** [comment]
Just tap the qr code area to show/hide the balance. This is intentional to allow someone to scan your QR code without displaying your balance

**Comment by old-greywolf** [comment]
OK, that toggles the balance display.

but the sync still stays at 0%

yesterday, and the few days before when i installed, it would get to 100% most of the time.

unless the display has changed and i didn't notice.
i hate to waste anyone's time in rabbit holes.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by zpalmtree** [comment]
Do you have an internet connection? Can you check the logger screen, and post the output here?

**Comment by old-greywolf** [comment]
Sent from ProtonMail mobile

-------- Original Message --------

**Comment by old-greywolf** [comment]
data limiting was enabled in settings (not by choice)

changed it, and it is syncing now

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by zpalmtree** [comment]
Good stuff. It should default to not limiting by the way, possibly you toggled it by accident? :man_shrugging:

**Comment by old-greywolf** [comment]
well, i can't rule that out, but i'm not in settings often, but still is possible for operator error :-)

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by wrkzdev** [comment]
I've experienced with this before too. Shall be there a FAQ?

**Comment by zpalmtree** [comment]
Experienced what, the data limit flipping?

**Comment by wrkzdev** [comment]
I always connected with WiFi. Once with 4G, it doesn't sync.
**Limit data** _Only sync when connected to WiFi_.
