### ISSUE TITLE
When adding recipients the app crashes

### ISSUE THREAD

**Issue by Nash-Cash** [turtlecoin/turtlecoin-mobile-wallet#48]
when adding a recipient to the address book or when sending, the app crashes and needs to be restarted. it happens during qr scanning, or when entering the address in the place: continue. Tested with Android 5.0 and 9.0. My addresses ar 98chars long and so I also have it in config.js

**Comment by Nash-Cash** [comment]
i dont know why but after: yarn build-android (problem above) i do eact-native log-android and get:

Starting the logger (adb logcat *:S ReactNative:V ReactNativeJS:V)...
adb server is out of date.  killing...
* daemon started successfully *
--------- beginning of system
--------- beginning of main
I/ReactNativeJS( 5140): [14:13:04]: Updating daemon info...
I/ReactNativeJS( 5140): [14:13:05]: Checking locked transactions...
I/ReactNativeJS( 5140): [14:13:05]: Saving wallet...
I/ReactNativeJS( 5140): [14:13:06]: Save complete.
I/ReactNativeJS( 5140): [14:13:07]: No blocks stored, fetching more.
I/ReactNativeJS( 5140): [14:13:08]: Zero blocks received from daemon, possibly fully synced
I/ReactNativeJS( 5140): [14:13:09]: No blocks stored, fetching more.
 ...

D/ReactNative( 5961): ReactInstanceManager.detachViewFromInstance()
D/ReactNative( 6614): ReactInstanceManager.ctor()
D/ReactNative( 6614): ReactInstanceManager.createReactContextInBackground()
D/ReactNative( 6614): ReactInstanceManager.recreateReactContextInBackgroundInner()
D/ReactNative( 6614): ReactInstanceManager.recreateReactContextInBackgroundFromBundleLoader()
D/ReactNative( 6614): ReactInstanceManager.recreateReactContextInBackground()
D/ReactNative( 6614): ReactInstanceManager.runCreateReactContextOnNewThread()
D/ReactNative( 6614): ReactInstanceManager.createReactContext()
D/ReactNative( 6614): Initializing React Xplat Bridge.
D/ReactNative( 6614): Initializing React Xplat Bridge before initializeBridge
D/ReactNative( 6614): Initializing React Xplat Bridge after initializeBridge
D/ReactNative( 6614): CatalystInstanceImpl.runJSBundle()
D/ReactNative( 7348): ReactInstanceManager.ctor()
D/ReactNative( 7348): ReactInstanceManager.createReactContextInBackground()
D/ReactNative( 7348): ReactInstanceManager.recreateReactContextInBackgroundInner()
D/ReactNative( 7348): ReactInstanceManager.recreateReactContextInBackgroundFromBundleLoader()
D/ReactNative( 7348): ReactInstanceManager.recreateReactContextInBackground()
D/ReactNative( 7348): ReactInstanceManager.runCreateReactContextOnNewThread()
D/ReactNative( 7348): ReactInstanceManager.createReactContext()
D/ReactNative( 7348): Initializing React Xplat Bridge.
D/ReactNative( 7348): Initializing React Xplat Bridge before initializeBridge
D/ReactNative( 7348): Initializing React Xplat Bridge after initializeBridge
D/ReactNative( 7348): CatalystInstanceImpl.runJSBundle()
D/ReactNative( 7505): ReactInstanceManager.ctor()
D/ReactNative( 7505): ReactInstanceManager.createReactContextInBackground()
D/ReactNative( 7505): ReactInstanceManager.recreateReactContextInBackgroundInner()
D/ReactNative( 7505): ReactInstanceManager.recreateReactContextInBackgroundFromBundleLoader()
D/ReactNative( 7505): ReactInstanceManager.recreateReactContextInBackground()
D/ReactNative( 7505): ReactInstanceManager.runCreateReactContextOnNewThread()
D/ReactNative( 7505): ReactInstanceManager.createReactContext()
D/ReactNative( 7505): Initializing React Xplat Bridge.
D/ReactNative( 7505): Initializing React Xplat Bridge before initializeBridge
D/ReactNative( 7505): Initializing React Xplat Bridge after initializeBridge
D/ReactNative( 7505): CatalystInstanceImpl.runJSBundle()
D/ReactNative( 7604): ReactInstanceManager.ctor()
D/ReactNative( 7604): ReactInstanceManager.createReactContextInBackground()
D/ReactNative( 7604): ReactInstanceManager.recreateReactContextInBackgroundInner()
D/ReactNative( 7604): ReactInstanceManager.recreateReactContextInBackgroundFromBundleLoader()
D/ReactNative( 7604): ReactInstanceManager.recreateReactContextInBackground()
D/ReactNative( 7604): ReactInstanceManager.runCreateReactContextOnNewThread()
D/ReactNative( 7604): ReactInstanceManager.createReactContext()
D/ReactNative( 7604): Initializing React Xplat Bridge.
D/ReactNative( 7604): Initializing React Xplat Bridge before initializeBridge
D/ReactNative( 7604): Initializing React Xplat Bridge after initializeBridge
D/ReactNative( 7604): CatalystInstanceImpl.runJSBundle()

**Comment by zpalmtree** [comment]
Seems the logs got truncated there? Upload to pastebin or something similar if the github formatting is killing it. I'm not seeing any errors in there, looks like the program is being loaded multiple times.

Keep running `react-native log-android` as you reproduce the error, it prints logs in real time.

If you still get no error in the logs, then it's possible the program is crashing due to native code. In that case, run `adb logcat`, and search through the logs for the initial crash and resulting stack trace, and post that instead.

**Comment by Nash-Cash** [comment]
it only says me (between the block log):

E/ReactNativeJS( 3399): Can't find variable: newPayee

**Comment by Nash-Cash** [comment]
![mobiele](https://user-images.githubusercontent.com/45920023/54196227-23b5ba80-44c1-11e9-8a91-062c102ce53e.jpg)

**Comment by zpalmtree** [comment]
Ok, that's what I was looking for. Please refork the code - I had some in progress changes which I made the day before yesterday, which have now been completed.

**Comment by Nash-Cash** [comment]
> Please refork the code -
This work for me
