### ISSUE TITLE
Failed to get wallet & daemon sync data

### ISSUE THREAD

**Issue by mimians** [turtlecoin/turtlecoin-mobile-wallet#51]
Forked well but the wallet & daemon sync fails with these error messages

No block store, fetching more
Failed to get wallet sync data: Error. Request failed
Zero blocks received from daemon, possibly fully synced

Please provide us with a step by step guide for setting up the server wallet API and configuring of the mobile wallet. Thanks

**Comment by zpalmtree** [comment]
>Failed to get wallet sync data: Error. Request failed
Sounds like a configuration error. I can't really provide any insight here, I am not running the blockchain cache API.

**Comment by LeinAd2k** [comment]
I have the same Problem above and i use a blockchain Cache api:
167.99.131.148/cache/info
and i have this in config:

defaultDaemon: new BlockchainCacheApi('167.99.131.148/cache', false),


im forking your wallet for some coins :-)

**Comment by zpalmtree** [comment]
It should be `defaultDaemon: new BlockchainCacheApi('167.99.131.148/cache', true),` if you're using ssl. Again, you'll need to check your cache api logs. I don't know how it works.
