### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by mimians** [turtlecoin/turtlecoin-mobile-wallet#59]
After rename package, this error happens

"Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 6s"
What do you think is the cause and how to fix it?

**Comment by zpalmtree** [comment]
The actual error should be listed above this output. Sometimes the build does just randomly fail, so try again to begin with. That said, I have not renamed the package before, so am unsure of what would cause it to fail.

**Comment by wrkzdev** [comment]
It ever happened to me also for the FORK. I just need to re-run the build command again and it just worked.

**Comment by zpalmtree** [comment]
Assuming this is fixed..
Feel free to reopen if not.
