### ISSUE TITLE
Pin verification taking very long

### ISSUE THREAD

**Issue by TheDOme6** [turtlecoin/turtlecoin-mobile-wallet#61]
In v0.0.7 after the last pin number is clicked, the app freezes for about 10-20 seconds and the displays the wallet. Is that normal?

**Comment by zpalmtree** [comment]
It is compacting the wallet database, if you close/open again, is it still very slow? Might just be the initial compaction is slow.

**Comment by TheDOme6** [comment]
Still very slow after several reopening. And I noticed some layout bugs on the pin verify screen.[image](https://i.postimg.cc/TxQ4hq2b/Screenshot-20190325-001357-01.jpg)

**Comment by zpalmtree** [comment]
Ok, i'll make it only compact occasionally. What model phone is that? Displays fine on the two devices I tested on.

**Comment by TheDOme6** [comment]
OnePlus 6T

**Comment by zpalmtree** [comment]
Altered compaction to not run on pin unlock. Not sure how to handle the pin verify screen.. works fine on all devices I tested, and I don't see it as an option to emulate.
