### ISSUE TITLE
Add a 'refresh' gesture to reload coin price

### ISSUE THREAD

**Issue by zpalmtree** [turtlecoin/turtlecoin-mobile-wallet#67]
You know that thing where you pull the screen down and it reloads stuff
Could probably also refresh balance while we're there since it has a 10s lag

**Comment by TheDOme6** [comment]
Some inspiration:

https://github.com/moschan/react-native-pull-to-refresh

https://github.com/syrusakbary/react-native-refresher

https://github.com/NadiKuts/react-native-pull-refresh

**Comment by zpalmtree** [comment]
We should also refresh when we come to the foreground. Pretty common to open up for a minute, close, and we never hit the auto refresh.

**Comment by TheDOme6** [comment]
https://stackoverflow.com/questions/33758390/react-native-android-activity-onpause-onresume

**Comment by zpalmtree** [comment]
Can do both these things without dependencies ;)
https://facebook.github.io/react-native/docs/appstate.html
https://facebook.github.io/react-native/docs/refreshcontrol.html

**Comment by zpalmtree** [comment]
Done
