### ISSUE TITLE
Transfer tab UI enhancements request

### ISSUE THREAD

**Issue by tatarenko** [turtlecoin/turtlecoin-mobile-wallet#72]
Transfer tab opens very different then all others - it appears as popup like window with back and close buttons. I think it is better to make it same appearance as all other parts of app so menu buttons don't suddenly disappear.

**Comment by zpalmtree** [comment]
I agree that it is a little jarring that the menu disappears. However, in all the pages on the transfer flow, we use a button that is flush with the bottom of the screen. I personally think this looks a lot better, but doesn't look good if the menu is there. I'm not sure if there's a way to get the best of both worlds.

**Comment by zpalmtree** [comment]
Since we re-ordered the menu to add the 'Who are you sending to' screen first, we can now just leave the tab bar there on the first menu, so when you're flicking through it's still simple, till you to to the next screen

**Comment by ExtraHash** [comment]
i still think it's better for the navigation to be consistant on every screen

**Comment by zpalmtree** [comment]
How do you suggest we implement the transfer screen instead then, because I think flush buttons look way better than floating ones.

**Comment by ExtraHash** [comment]
i think having the continue button right below the form and right-aligned while leaving the menu intact would be less confusing for users, is looking slightly better worth the jarring effect of having the navigation appear? alternatively you could just put the continue button directly over the navigation

**Comment by ExtraHash** [comment]
the continue button is already hovering over the system navigation bar anyways so i dont think it would look that bad to have three layers vs 2

**Comment by zpalmtree** [comment]
Not sure what you mean by having the button right aligned. It looks like this if we stack them, which imo, looks pretty bad:

![image](https://user-images.githubusercontent.com/22151537/61581948-eb805180-ab1c-11e9-9d99-e17ccd926878.png)

It looks like this without the tab bar present:
![image](https://user-images.githubusercontent.com/22151537/61581982-14a0e200-ab1d-11e9-81bc-4f3f06cb27a1.png)

And it looks like this if we use a floating button instead:
![image](https://user-images.githubusercontent.com/22151537/61582105-6dbd4580-ab1e-11e9-912f-d4dc9d99087c.png)

**Comment by zpalmtree** [comment]
If you think keeping the tab bar always present is best, then the last option probably is the best one.

**Comment by zpalmtree** [comment]
I decided to go with just showing the tab bar on the first screen. I think it looks better, and there are other similar apps which use this pattern, and it still seems intuitive.

**Comment by ExtraHash** [comment]
i think the floating button looks fine
