### ISSUE TITLE
Strange Recipients gets value

### ISSUE THREAD

**Issue by tatarenko** [turtlecoin/turtlecoin-mobile-wallet#73]
![WhatsApp Image 2019-04-04 at 01 01 56](https://user-images.githubusercontent.com/4854544/55516357-a6bbd200-5675-11e9-81b0-66b6d4647400.jpeg)
Why it's always cut 0.5%?
When i am using zedwallet default fee is 0.10 TRTL. Sure i am always raise it a little just to tip miners but 5k is little bit too much.

**Comment by zpalmtree** [comment]
It's the dev fee that is 0.5%, not the network fee. See the confirmation screen for the fee breakdown.

**Comment by tatarenko** [comment]
Think we should put it on this screen cause if number looks strange to you, you don't fill safe to press continue cause you don't know whats next

**Comment by zpalmtree** [comment]
Maybe we could change the bottom button to say 'Preview Transaction' instead of 'Continue', would that be sufficient? It would get a little cramped on this screen I feel to add the fee breakdown.

We could also maybe add a little '?' that can be toggled to show the fees I suppose.

**Comment by tatarenko** [comment]
Also just as suggestion, it could be nice move to make dev fee optional/configurable in settings. So default 0.5 and user could raise or lower.

**Comment by tatarenko** [comment]
I think fee breakdown is good chose - you put number, you get new number dynamically, think you should get explains right here. Also maybe user could raise transaction fee here optionally?
