### ISSUE TITLE
Nothing happens after enter PIN

### ISSUE THREAD

**Issue by tatarenko** [turtlecoin/turtlecoin-mobile-wallet#75]
When I enter PIN nothing happens. Just hangs forever.

**Environment**
- App version: [v0.1.0] 
- Phone model: Xiaomi a2 lite

**Comment by zpalmtree** [comment]
Are you creating a new wallet, or opening a wallet from a previous version?

**Comment by zpalmtree** [comment]
No response, closing for now.
