### ISSUE TITLE
fork guide

### ISSUE THREAD

**Issue by altcoin-services** [turtlecoin/turtlecoin-mobile-wallet#79]
hello,
we need to modify turtlecoin-wallet-backend and turtlecoin-crypto and their dependencies for other cryptonote based coins other than turtlecoin , right?

**Comment by zpalmtree** [comment]
No, the config from this repo is passed through to both of those.

**Comment by zpalmtree** [comment]
Well --- depends how different from TRTL they are. If they are not a TurtleCoin fork, then yes, you would probably need some modification. It certainly will not work with a Monero fork without large modification, for example.
