### ISSUE TITLE
Problems with android.support.v4

### ISSUE THREAD

**Issue by PaulWzlff** [turtlecoin/turtlecoin-mobile-wallet#82]
Hi Guys,

i forked your repository and followed the steps for the installation. The plan is to open this project in AndroidStudio. 
My problem is, that the package "android.support.v4.net.ConnectivityManagerCompat" in the class "ConnectivityReceiver" cant be found. I have tried to add the dependency in the modules, but that didn´t work.
![Image](https://user-images.githubusercontent.com/37270756/59878536-da6ee400-93a8-11e9-8c84-d17d2e513ab5.PNG)
Do you have any advises for me?

Thanks in advance.

**Comment by zpalmtree** [comment]
If you didn't fork in the past 16 hours or so, pull the latest code, see https://github.com/turtlecoin/turtlecoin-mobile-wallet/issues/80

If you did, try building anyway, ensuring you follow the steps on the readme. I have not used Android Studio to open the project and have no idea if it works or not. That library needs hacking to get compile working.
