### ISSUE TITLE
Rename Project?

### ISSUE THREAD

**Issue by brandonlehmann** [turtlecoin/turtlecoin-mobile-wallet#93]
Please rename the project `A Better Mobile Wallet`

**Comment by zpalmtree** [comment]
If it's not related to cute anime girls can you really call it a better name?

**Comment by elkimek** [comment]
+1

**Comment by Mufalo** [comment]
+1 for "Oneesama proton wallet"

**Comment by wrkzdev** [comment]
`Palm Wallet`
